import type { LoanOffer, LoanAgreement } from '@/entities/loan'

// Sample loan data - in production, this would come from an API
const SAMPLE_AVAILABLE_LOANS: LoanOffer[] = [
  {
    id: 1,
    maker: 'xch1abc...4f2a',
    assetType: 'CAT',
    amount: 10000,
    currency: 'b.USDC',
    interestRate: 8.5,
    duration: 12,
    collateralAssetType: 'XCH',
    collateralType: 'XCH',
    collateralRatio: 150,
    optionType: 'Call',
    strikePrice: 35,
    status: 'available',
  },
  {
    id: 2,
    maker: 'xch1def...7e3b',
    assetType: 'CAT',
    amount: 5000,
    currency: 'b.USDC',
    interestRate: 6.2,
    duration: 6,
    collateralAssetType: 'XCH',
    collateralType: 'XCH',
    collateralRatio: 130,
    optionType: 'Put',
    strikePrice: 30,
    status: 'available',
  },
  {
    id: 3,
    maker: 'xch1ghi...9d1c',
    assetType: 'CAT',
    amount: 25000,
    currency: 'b.USDT',
    interestRate: 10.0,
    duration: 24,
    collateralAssetType: 'XCH',
    collateralType: 'XCH',
    collateralRatio: 175,
    optionType: 'Call',
    strikePrice: 40,
    status: 'available',
  },
  {
    id: 4,
    maker: 'xch1jkl...2e4f',
    assetType: 'CAT',
    amount: 15000,
    currency: 'b.USDC',
    interestRate: 7.8,
    duration: 18,
    collateralAssetType: 'XCH',
    collateralType: 'XCH',
    collateralRatio: 160,
    optionType: 'Call',
    strikePrice: 38,
    status: 'available',
  },
  {
    id: 5,
    maker: 'xch1mno...1c3d',
    assetType: 'CAT',
    amount: 3000,
    currency: 'b.USDT',
    interestRate: 5.5,
    duration: 3,
    collateralAssetType: 'XCH',
    collateralType: 'XCH',
    collateralRatio: 140,
    optionType: 'Put',
    strikePrice: 32,
    status: 'available',
  },
  {
    id: 6,
    maker: 'xch1pqr...8b7a',
    assetType: 'CAT',
    amount: 50000,
    currency: 'b.USDC',
    interestRate: 11.5,
    duration: 36,
    collateralAssetType: 'XCH',
    collateralType: 'XCH',
    collateralRatio: 180,
    optionType: 'Call',
    strikePrice: 45,
    status: 'available',
  },
  {
    id: 7,
    maker: 'xch1stu...9f1a',
    assetType: 'NFT',
    nftCollection: 'ChiaPunks',
    nftTokenId: '#2547',
    amount: 50,
    currency: 'XCH',
    interestRate: 12.0,
    duration: 6,
    collateralAssetType: 'NFT',
    collateralNftCollection: 'ChiaArt',
    collateralType: 'NFT',
    collateralRatio: 120,
    status: 'available',
  },
  {
    id: 8,
    maker: 'xch1vwx...2b8e',
    assetType: 'CAT',
    amount: 8000,
    currency: 'b.USDC',
    interestRate: 9.5,
    duration: 12,
    collateralAssetType: 'NFT',
    collateralNftCollection: 'ChiaCollectibles',
    collateralType: 'NFT',
    collateralRatio: 150,
    status: 'available',
  },
  {
    id: 9,
    maker: 'xch1yza...4c1d',
    assetType: 'Options',
    optionUnderlying: 'XCH',
    optionContractType: 'Call',
    optionStrike: 36,
    optionQuantity: 5,
    amount: 3500,
    currency: 'b.USDC',
    interestRate: 15.0,
    duration: 3,
    collateralAssetType: 'XCH',
    collateralType: 'XCH',
    collateralRatio: 200,
    status: 'available',
  },
]

const SAMPLE_MY_LOANS_TAKEN: LoanAgreement[] = [
  {
    id: 202,
    lender: 'xch1bcd...4a1f',
    maker: 'xch1bcd...4a1f',
    amount: 8000,
    currency: 'b.USDC',
    interestRate: 9.0,
    duration: 12,
    monthlyPayment: 702,
    totalRepayment: 8424,
    collateralProvided: 5.5,
    collateralType: 'XCH',
    optionType: 'Call',
    strikePrice: 35,
    startDate: '2024-09-01',
    nextPayment: '2024-11-01',
    paymentsRemaining: 10,
    status: 'funded',
    assetType: 'CAT',
    collateralAssetType: 'XCH',
    collateralRatio: 150,
  },
]

const SAMPLE_MY_CREATED_LOANS: LoanOffer[] = [
  {
    id: 301,
    maker: 'xch1CurrentUser',
    assetType: 'CAT',
    amount: 15000,
    currency: 'b.USDC',
    interestRate: 8.0,
    duration: 12,
    collateralAssetType: 'XCH',
    collateralType: 'XCH',
    collateralRatio: 160,
    status: 'funded',
    borrower: 'xch1abc1...2def',
    fundedDate: '2024-10-15',
  },
]

export function useLoansData() {
  return {
    availableLoans: SAMPLE_AVAILABLE_LOANS,
    myLoansTaken: SAMPLE_MY_LOANS_TAKEN,
    myCreatedLoans: SAMPLE_MY_CREATED_LOANS,
  }
}
