import type { LoanOffer, LoanAgreement } from '@/types/loan.types'

// Sample loan data - in production, this would come from an API
const SAMPLE_AVAILABLE_LOANS: LoanOffer[] = [
  {
    id: 1,
    maker: '0x742d...4f2a',
    assetType: 'ERC20',
    amount: 10000,
    currency: 'USDC',
    interestRate: 8.5,
    duration: 12,
    collateralAssetType: 'ERC20',
    collateralType: 'ETH',
    collateralRatio: 150,
    optionType: 'Call',
    strikePrice: 2500,
    status: 'available',
  },
  {
    id: 2,
    maker: '0x891c...7e3b',
    assetType: 'ERC20',
    amount: 5000,
    currency: 'USDC',
    interestRate: 6.2,
    duration: 6,
    collateralAssetType: 'ERC20',
    collateralType: 'BTC',
    collateralRatio: 130,
    optionType: 'Put',
    strikePrice: 45000,
    status: 'available',
  },
  {
    id: 3,
    maker: '0x234a...9d1c',
    assetType: 'ERC20',
    amount: 25000,
    currency: 'DAI',
    interestRate: 10.0,
    duration: 24,
    collateralAssetType: 'ERC20',
    collateralType: 'ETH',
    collateralRatio: 175,
    optionType: 'Call',
    strikePrice: 3000,
    status: 'available',
  },
  {
    id: 4,
    maker: '0x567d...2e4f',
    assetType: 'ERC20',
    amount: 15000,
    currency: 'USDT',
    interestRate: 7.8,
    duration: 18,
    collateralAssetType: 'ERC20',
    collateralType: 'SOL',
    collateralRatio: 160,
    optionType: 'Call',
    strikePrice: 120,
    status: 'available',
  },
  {
    id: 5,
    maker: '0x9a8b...1c3d',
    assetType: 'ERC20',
    amount: 3000,
    currency: 'DAI',
    interestRate: 5.5,
    duration: 3,
    collateralAssetType: 'ERC20',
    collateralType: 'ETH',
    collateralRatio: 140,
    optionType: 'Put',
    strikePrice: 2400,
    status: 'available',
  },
  {
    id: 6,
    maker: '0x1f2e...8b7a',
    assetType: 'ERC20',
    amount: 50000,
    currency: 'USDC',
    interestRate: 11.5,
    duration: 36,
    collateralAssetType: 'ERC20',
    collateralType: 'BTC',
    collateralRatio: 180,
    optionType: 'Call',
    strikePrice: 50000,
    status: 'available',
  },
  {
    id: 7,
    maker: '0x3d4e...9f1a',
    assetType: 'NFT',
    nftCollection: 'BAYC',
    nftTokenId: '#2547',
    amount: 50,
    currency: 'ETH',
    interestRate: 12.0,
    duration: 6,
    collateralAssetType: 'NFT',
    collateralNftCollection: 'CryptoPunks',
    collateralType: 'NFT',
    collateralRatio: 120,
    status: 'available',
  },
  {
    id: 8,
    maker: '0x6c7d...2b8e',
    assetType: 'ERC20',
    amount: 8000,
    currency: 'USDC',
    interestRate: 9.5,
    duration: 12,
    collateralAssetType: 'NFT',
    collateralNftCollection: 'Azuki',
    collateralType: 'NFT',
    collateralRatio: 150,
    status: 'available',
  },
  {
    id: 9,
    maker: '0x8e9f...4c1d',
    assetType: 'Options',
    optionUnderlying: 'ETH',
    optionContractType: 'Call',
    optionStrike: 2800,
    optionQuantity: 5,
    amount: 3500,
    currency: 'USDC',
    interestRate: 15.0,
    duration: 3,
    collateralAssetType: 'ERC20',
    collateralType: 'ETH',
    collateralRatio: 200,
    status: 'available',
  },
]

const SAMPLE_MY_LOANS_TAKEN: LoanAgreement[] = [
  {
    id: 202,
    lender: '0x789e...4a1f',
    maker: '0x789e...4a1f',
    amount: 8000,
    currency: 'USDC',
    interestRate: 9.0,
    duration: 12,
    monthlyPayment: 702,
    totalRepayment: 8424,
    collateralProvided: 5.5,
    collateralType: 'ETH',
    optionType: 'Call',
    strikePrice: 2600,
    startDate: '2024-09-01',
    nextPayment: '2024-11-01',
    paymentsRemaining: 10,
    status: 'funded',
    assetType: 'ERC20',
    collateralAssetType: 'ERC20',
    collateralRatio: 150,
  },
]

const SAMPLE_MY_CREATED_LOANS: LoanOffer[] = [
  {
    id: 301,
    maker: '0xCurrentUser',
    assetType: 'ERC20',
    amount: 15000,
    currency: 'USDC',
    interestRate: 8.0,
    duration: 12,
    collateralAssetType: 'ERC20',
    collateralType: 'ETH',
    collateralRatio: 160,
    status: 'funded',
    borrower: '0xabc1...2def',
    fundedDate: '2024-10-15',
  },
]

export function useLoansData() {
  return {
    availableLoans: SAMPLE_AVAILABLE_LOANS,
    myLoansTaken: SAMPLE_MY_LOANS_TAKEN,
    myCreatedLoans: SAMPLE_MY_CREATED_LOANS,
  }
}
